version: '3.8'
services:
  web_app:
    image: nginx:alpine
    container_name: production_web
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
